`(  (axiom       . "FX" )
    (angle       . 45  )
    (line-length . 3  )
    (iteration   . 10  )
    (start-x     . 200 )
    (start-y     . 200 )
	(start-angle . 90  )
	(rules       . ((#\F  . "")
                    (#\X  . "-FX++FY-")
					(#\Y  . "+FX--FY+"))))