`(  (axiom       . "X"  )
    (angle       . 90  )
    (line-length . 3  )
    (iteration   . 6   )
    (start-x     . 200 )
    (start-y     . 500 )
	(start-angle . 180 )
	(rules       . ((#\X  . "-YF+XFX+FY-")
                    (#\Y  . "+XF-YFY-FX+"))))