`(  (axiom       . "X"  )
    (angle       . 90  )
    (line-length . 3  )
    (iteration   . 4   )
    (start-x     . 500 )
    (start-y     . 500 )
	(start-angle . 180 )
	(rules       . ((#\X  . "XFYFX+F+YFXFY-F-XFYFX")
                    (#\Y  . "YFXFY-F-XFYFX+F+YFXFY"))))