`(  (axiom       . "AF"  )
    (angle       . 45  )
    (line-length . 3  )
    (iteration   . 3   )
    (start-x     . 400 )
    (start-y     . 500 )
	(start-angle . 180 )
	(rules       . ((#\A  . "AF+F+BF-F-AF-F-BF-F-AF+F+BF+F+AF+F+BF-F-A")
                    (#\B  . "BF-F-AF+F+BF+F+AF+F+BF-F-AF-F-BF-F-AF+F+B"))))