`(  (axiom       . "L--F--L--F"  )
    (angle       . 45  )
    (line-length . 3  )
    (iteration   . 10 )
    (start-x     . 400 )
    (start-y     . 500 )
	(start-angle . 180 )
	(rules       . ((#\L  . "+R-F-R+")
                    (#\R  . "-L+F+L-"))))