`(  (axiom       . "-L"  )
    (angle       . 90  )
    (line-length . 3  )
    (iteration   . 4   )
    (start-x     . 100 )
    (start-y     . 500 )
	(start-angle . 180 )
	(rules       . ((#\R  . "-LFLF+RFRFR+F+RF-LFL-FR")
                    (#\L  . "LF+RFR+FL-F-LFLFL-FRFR+"))))