`(  (axiom       . "L"  )
    (angle       . 60  )
    (line-length . 2   )
    (iteration   . 7   )
    (start-x     . 300 )
    (start-y     . 500 )
	(start-angle . 90  )
	(rules       . ((#\L  . "+R-L-R+")
                    (#\R  . "-L+R+L-"))))