`(  (axiom       . "++++F"  )
    (angle       . 22.5 )
    (line-length . 6   )
    (iteration   . 5   )
    (start-x     . 300 )
    (start-y     . 500 )
	(start-angle . 90  )
	(rules       . ((#\F  . "FF-[XY]+[XY]")
                    (#\X  . "+FY")
					(#\Y  . "-FY"))))