`(  (axiom       . "Z"  )
    (angle       . 30  )
    (line-length . 4   )
    (iteration   . 5   )
    (start-x     . 300 )
    (start-y     . 500 )
	(start-angle . 180 )
	(rules       . ((#\X  . "X[-FFF][+FFF]FX")
                    (#\Z  . "ZFX[+Z][-Z]"))))