`(  (axiom       . "X"  )
    (angle       . 20  )
    (line-length . 6   )
    (iteration   . 5   )
    (start-x     . 300 )
    (start-y     . 500 )
	(start-angle . 180 )
	(rules       . ((#\F  . "FF")
                    (#\X  . "F[+X]F[-X]+X"))))