`(  (axiom       . "F" )
    (angle       . 25  )
    (line-length . 8   )
    (iteration   . 4   )
    (start-x     . 300 )
    (start-y     . 400 )
	(start-angle . 180 )
	(rules       . ((#\F  . "F[+F]F[-F+F]"))))