`(  (axiom       . "X"  )
    (angle       . 30  )
    (line-length . 4   )
    (iteration   . 5   )
    (start-x     . 300 )
    (start-y     . 500 )
	(start-angle . 180 )
	(rules       . ((#\X  . "FX[-FYF][+FYF]XF")
                    (#\Y  . "YFX[+Y][-Y]"))))