`(  (axiom       . "G"  )
    (angle       . 2   )
    (line-length . 4   )
    (iteration   . 5   )
    (start-x     . 300 )
    (start-y     . 500 )
	(start-angle . 180 )
	(rules       . ((#\G  . "GFX[+++++GFG][-----GFG]")
                    (#\X  . "F-XF"))))