`(  (axiom       . "G"  )
    (angle       . 30  )
    (line-length . 4   )
    (iteration   . 6   )
    (start-x     . 300 )
    (start-y     . 500 )
	(start-angle . 180 )
	(rules       . ((#\G  . "[+FGF][-FGF]XG")
                    (#\X  . "XFX"))))