`(  (axiom       . "F" )
    (angle       . 25  )
    (line-length . 10  )
    (iteration   . 5   )
    (start-x     . 300 )
    (start-y     . 400 )
	(start-angle . 180 )
	(rules       . ((#\F  . "F[-F][+F]F"))))