`(  (axiom       . "F" )
    (angle       . 20  )
    (line-length . 6   )
    (iteration   . 4   )
    (start-x     . 300 )
    (start-y     . 500 )
	(start-angle . 180 )
	(rules       . ((#\F  . "F[-F][+F][--F]F[++F]F"))))